user nginx;
worker_processes 1;

# error_log  /var/log/nginx/error.log warn;
#pid        /var/run/nginx/nginx.pid;


events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile off;
    keepalive_timeout 60;
    server_tokens off;
    #gzip on;

    include /etc/nginx/conf.d/*.conf;
}
